name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Patch vss-extension.json
        uses: onlyutkarsh/patch-files-action@v1.0.3
        with:
          files: vss-extension.json
          patch-syntax: = /version => "0.1.${{ github.run_number }}"
          fail-if-no-files-patched: true

      - name: Patch task.json
        uses: onlyutkarsh/patch-files-action@v1.0.3
        with:
          files: task/task.json
          patch-syntax: |
            = /version/Major => "0"
            = /version/Minor => "1"
            = /version/Patch => "${{ github.run_number }}"
          fail-if-no-files-patched: true

      - name: Build task (ts -> task/dist/index.js)
        run: npm run build

      - name: Install tfx
        run: npm i -g tfx-cli@latest
        
      - name: Build vsix
        run: tfx extension create --manifest-globs vss-extension.json
      
      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: ./*.vsix
          if-no-files-found: error

      - name: Create Release
        if: ${{ github.event_name == 'push' }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./elmahio.broken-links-checker-0.1.${{ github.run_number }}.vsix
          tag_name: 0.1.${{ github.run_number }}
          name: 0.1.${{ github.run_number }}
          draft: false
          fail_on_unmatched_files: true
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}